name: Release

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Package

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: publishHtmlTask
        run: |
          npm install
          sudo npm install -g tfx-cli

      - name: Prepare Task
        working-directory: publishHtmlTask
        run: |
          tsc
          mv task.release.json task.json

      - name: Rev Manifest
        run: |
          new_version=$(echo ${GITHUB_REF##*/} | sed -e 's/^v//')
          json=$(cat vss-extension.json | jq --arg v "${new_version}" '.version = $v')
          echo $json > vss-extension.json

      - name: Publish Extension
        run: |
          tfx extension publish -t ${{ secrets.MarketplaceToken }} --manifests vss-extension.json